### ISSUE TITLE
Separar el codigo en carpetas jerarquicas.

### ISSUE THREAD

**Issue by Nachiten** [Nachiten/QueueBot#3]
**Src:**
- Main
- Comandos: Todos los comandos
- Configs: discordToken, globalVariables, configs
- Utils: utils.
- Adapter: ModuloAdapter

**Tests:**
- Todos los tests automatizados

**Comment by Nachiten** [comment]
@RaniAgus Actualicé esto para asegurarnos que por un lado esté todo el código fuente (src) y luego en otra carpeta los tests (carpeta tests)

**Comment by RaniAgus** [comment]
Por lo que vi si en PyCharm creás los packages con "New Python Package" (o algo así) y arrastrás los `*.py` el IDE los actualiza todos

Queda medio berreta pero es mejor que nada :P
